import ImageAssets from '../../assets/imageAsset';

export const assessmentSummaryColumns = [
  {
    column_key: {
      D: 'assessment_date',
      M: 'assessment_month',
      Y: 'assessment_date',
    },
    columnName: 'DATE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'date',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_group_session_code',
    columnName: 'ASSESSMENT',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'topic_name',
    columnName: 'TITLE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_mode_name',
    columnName: 'MODE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_type_name',
    columnName: 'TYPE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_organizer_name',
    columnName: 'ORGANIZER',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'study_circle_name',
    columnName: 'STUDY CIRCLE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'count_present_students',
    columnName: 'ATTENDANCE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'attendance',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'avg_velocity',
    columnName: 'Avg. Velocity',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.tableSpeedometer}`,
    className: 'px-4 py-3 flex h-full items-center justify-center',
    resType: 'scoreFlag',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'count_hand_raises',
    columnName: 'Handrise',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.handraise}`,
    className: 'px-4 py-3',
    imgClassName: 'max-w-6',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'count_correct_responses',
    columnName: 'RESULT',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'graph',
    resStyle: 'px-4 py-3 text-center',
  },
];
