import ImageAssets from '../../assets/imageAsset';

export const studyCircleSummaryCol = [
  {
    column_key: 'study_circle_name',
    columnName: 'STUDY CIRCLE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'subject_name',
    columnName: 'SUBJECT',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_mode_name',
    columnName: 'MODE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_type_name',
    columnName: 'TYPE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'assessment_organizer_name',
    columnName: 'ORGANIZER',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'count_total_questions',
    columnName: 'QUESTIONS',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'questions',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'avg_response_main_score',
    columnName: 'SCORE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'scoreFlag',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'avg_response_velocity',
    columnName: 'Avg. Velocity',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.tableSpeedometer}`,
    className: 'px-4 py-3 flex h-full items-center justify-center',
    resType: 'scoreFlag',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'group_percentile',
    columnName: 'GROUP PERCENTILE',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'sc_trend',
    columnName: 'Trend',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.trend}`,
    className: 'px-4 py-3',
    imgClassName: 'max-w-6',
    resType: 'img',
    resStyle: 'px-4 py-3',
  },
];
