import ImageAssets from '../../assets/imageAsset';

export const studentSummaryColumns = [
  {
    column_key: 'student_id',
    columnName: 'R#',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'student_name',
    columnName: 'Name',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'study_circle_name',
    columnName: 'Study Circle',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'count_present_questions',
    columnName: 'Questions',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'questions',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'avg_score',
    columnName: 'Score',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'scoreFlag',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'avg_velocity',
    columnName: 'Avg. Velocity',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.tableSpeedometer}`,
    className: 'px-4 py-3 flex h-full items-center justify-center',
    resType: 'scoreFlag',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'study_circle_rank',
    columnName: 'Study Circle Rank',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'group_percentile',
    columnName: 'Group Percentile',
    hasSort: false,
    columnType: 'text',
    className: 'px-4 py-3',
    resType: 'text',
    resStyle: 'px-4 py-3 text-center',
  },
  {
    column_key: 'student_trend',
    columnName: 'Trend',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.trend}`,
    className: 'px-4 py-3',
    imgClassName: 'max-w-6',
    resType: 'img',
    resStyle: 'px-4 py-3',
  },
  {
    column_key: 'count_hand_raises',
    columnName: 'Handrise',
    hasSort: false,
    columnType: 'image',
    imagePath: `${ImageAssets.handraise}`,
    className: 'px-4 py-3',
    imgClassName: 'max-w-6',
    resType: 'text',
    resStyle: 'px-4 py-3',
  },
];
